version: '3'
services:
  redis:
    container_name: hwhong_redis_1
    image: redis
    command: redis-server --requirepass 1234 --port 6379
    ports:
      - 6379:6379
  
  flower:
    container_name: hwhong_flower_1
    build:
      context: .
    restart: always
    depends_on:
      - redis
    environment:
      - EXECUTOR=Celery
      # - REDIS_PASSWORD=redispass
    ports:
      - "5555:5555"
    command: flower   

  nginx:
    container_name: hwhong_nginx_1
    build:
      context: .
      dockerfile: config/nginx/Dockerfile
    #image: library/nginx:latest
    ports:
      - '80:80'
    volumes:
      - .:/code
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      #- ./config/nginx:/etc/nginx/conf.d
      - ./backend/staticfiles:/code/staticfiles
    depends_on:
      - django
       
  django:
    container_name: hwhong_django_1
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
    environment:
      - LANG=ko_KR.UTF-8
      - LANGUAGE=ko_KR.UTF-8
    expose:
      - '8000'
    depends_on:
      - db
    restart: always
    command: ./backend/script/django-entrypoint.sh

  db:
    image: gusdn90/postgres9.6:1.0
    container_name: hwhong_postgres_1
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASS=${POSTGRES_PASS}
      - POSTGRES_DBNAME=${POSTGRES_DBNAME}
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: "pg_isready -h localhost -p 5432 -q -U postgres"
      interval: 3s
      timeout: 1s
      retries: 10
